[package]
name = "opman"
version = "0.0.1"
edition = "2021"

[dependencies]
alpm = "2.2.1"
bytesize = "1.1.0"
chrono = "0.4.19"
clap = "3.1.6"
fern = {version = "0.6.0", features = ["colored"]}
log = "0.4.16"
pbr = "1.0.4"
